"""Real-model workspace attachment and rejection checks in headed Chrome."""
import hashlib
import json
import re
import subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
from live_plugin_browser import BASE, LivePluginBrowser

WORKTREE = Path('/Volumes/librefang/worktrees/plugin-functional-verification')
fixture = json.loads(subprocess.check_output(
    ['node', 'scripts/fixtures/plugin-verification/at-file.mjs'], cwd=WORKTREE, text=True,
))
files = fixture['files']

def digests():
    return {key: hashlib.sha256((WORKTREE / path).read_bytes()).hexdigest()
            for key, path in files.items() if key not in {'missing', 'directory'}}

before = digests()
try:
    with sync_playwright() as p:
        audit = LivePluginBrowser(p, ['at-file'])
        def panel(texts):
            audit.page.get_by_role('button', name='插件，已安装', exact=False).click()
            audit.page.get_by_role('button', name=re.compile(r'^查看 @file .*详情$')).click()
            card = audit.page.locator('.plugin-panel-card').filter(has_text='file_context')
            for text in texts:
                expect(card.get_by_text(text, exact=True)).to_be_visible()
            card.scroll_into_view_if_needed()
            audit.page.screenshot(path='/tmp/pih-at-file.png')
            audit.page.locator('button.session-row.active').click()
            print('at_file panel PASS', flush=True)
        try:
            result = audit.invoke('file_context', {'path': files['valid']})
            assert not result['isError']
            byte_count = len(fixture['text'].encode())
            assert result['details'] == {'path': files['valid'], 'bytes': byte_count}
            framed = result['content'][0]['text']
            expected = fixture['text'].replace('</file>', '<\\/file>')
            assert framed == f'<file path="{files["valid"]}" untrusted="true">\n{expected}\n</file>'
            assert framed.count('</file>') == 1
            panel([f'{files["valid"]} · {byte_count} bytes', '262144 bytes'])
            for kind, message in [
                ('oversized', '256 KiB'), ('invalid', 'valid UTF-8'), ('nul', 'NUL'),
                ('escape', 'inside the current workspace'), ('symlink', 'inside the current workspace'),
                ('missing', 'inside the current workspace'), ('directory', 'not a file'),
            ]:
                result = audit.invoke('file_context', {'path': files[kind]})
                assert result['isError'] and message in result['content'][0]['text'], kind
                assert 'SYNTHETIC_OUTSIDE_MUST_NOT_BE_RETURNED' not in json.dumps(result), kind
                panels = audit.page.request.get(BASE + '/api/plugin-ui', max_retries=2).json()['items']
                data = next(item['data'] for item in panels if item['id'] == 'at-file-panel')
                assert data['lastFile'] == {'path': files['valid'], 'bytes': byte_count}, kind
                print('rejected_' + kind + ' PASS', flush=True)
            panel([f'{files["valid"]} · {byte_count} bytes'])
            empty = audit.invoke('file_context', {'path': files['empty']})
            assert not empty['isError'] and empty['details'] == {'path': files['empty'], 'bytes': 0}
            panel([f'{files["empty"]} · 0 bytes'])
            assert digests() == before, 'Attachment tools must not mutate their inputs'
            audit.new_session()
            panel(['还没有附加文件。可使用 @file 或让 Agent 调用 file_context。'])
            audit.finish()
            print('at_file PASS', flush=True)
        finally:
            audit.close()
finally:
    # Only remove exact files generated by this invocation, not a recursive tree.
    for key, path in files.items():
        if key not in {'missing', 'directory'}:
            (WORKTREE / path).unlink(missing_ok=True)
    Path(fixture['root']).rmdir()
    Path(fixture['outside']).rmdir()
